#!/usr/bin/python

import os, os.path
import sys
import subprocess
import doctest
import traceback

python_path = os.path.abspath(os.path.dirname(__file__))
print "python_path", python_path

def call(input):
    child = subprocess.Popen((sys.executable,),
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                             env={'PYTHONPATH': python_path})
    out = child.communicate('\n'.join(line.strip()
                                      for line in input.split('\n')))[0]
    lines = out.split('\n')
    while len(lines) > 0 and not lines[-1]: del lines[-1]
    #print "lines:", lines
    for line in lines[:-1]: print line
    if lines:
        return tuple(int(x) for x in lines[-1].split())
    return 1, 0

errors = 0
tests = 0
files = 0

for dirpath, dirnames, filenames in os.walk('.'):
    if '.hg' in dirnames: dirnames.remove('.hg')
    for filename in filenames:
        path = os.path.join(dirpath, filename)
        try:
            if filename.endswith('.py'):
                print "Testing", path
                arg = os.path.normpath(path[:-3])
                arg = arg.replace(os.sep, '.')
                if os.sep != '/': arg = arg.replace('/', '.')

                e, t = call("""
                    import %(modpath)s
                    %(modpath)s.doing_doctest = True
                    import doctest

                    ans = doctest.testmod(%(modpath)s)
                    print ans[0], ans[1]
                """ % {'modpath': arg})
            elif filename.endswith('.tst'):
                print "Testing", path
                e, t = call("""
                    import doctest

                    ans = doctest.testfile('%(path)s', False)
                    print ans[0], ans[1]
                """ % {'path': path})
            else:
                e = t = 0
        except Exception:
            e, t = 1, 0
            traceback.print_exc()
        errors += e
        tests += t
        files += 1

print "Files: %d, Tests: %d, Errors: %d" % (files, tests, errors)
sys.exit(errors)
