#!/usr/bin/python

import os
import sys
import doctest
import traceback

#print "sys.path[0:2]", sys.path[0:2]
#sys.path.insert(0, '.')

def mod_import(modulepath):
    ''' modulepath does not include .py
    '''
    mod = __import__(modulepath)
    for comp in modulepath.split('.')[1:]:
        mod = getattr(mod, comp)
    return mod

errors = 0
tests = 0
files = 0

for dirpath, dirnames, filenames in os.walk('.'):
    if '.hg' in dirnames: dirnames.remove('.hg')
    for filename in filenames:
        path = os.path.join(dirpath, filename)
        try:
            if filename.endswith('.py'):
                print "Testing", path
                arg = os.path.normpath(path[:-3])
                arg = arg.replace(os.sep, '.')
                if os.sep != '/': arg = arg.replace('/', '.')
                mod = mod_import(arg)
                mod.doing_doctest = True
                e, t = doctest.testmod(mod)
            elif filename.endswith('.tst'):
                print "Testing", path
                e, t = doctest.testfile(path, False)
            else:
                e = t = 0
        except Exception:
            e, t = 1, 0
            traceback.print_exc()
        errors += e
        tests += t
        files += 1

print "Files: %d, Tests: %d, Errors: %d" % (files, tests, errors)
sys.exit(errors)
