#!/bin/bash

# backup db

usage() {
    echo "usage: backup db_file" >&2
    exit 2
}

[ $# -eq 1 ] || usage

set -e

db_backup_dir=backups

db="$1"
dir=`dirname "$db"`

rm -f "$dir/$db_backup_dir"/*.csv

backup.py "$db"
