#!/bin/bash

usage() {
    echo "usage: create_db directory" >&2
    exit 2
}

[ $# -eq 1 ] || usage

db_filename=python-avr.db
db_backup_dir=backups

set -e

dir="$1"
db="$dir/$db_filename"

if [ -e "$db" ]
then
    if [ `find -H "$dir/$db_backup_dir" -type f \! -newer "$db" | wc -l` -ne 0 ]
    then
        echo "You did not backup your database first!" >&2
        exit 1
    fi
fi

# Nuke the database!
rm -f "$db"

# Create a new database with the definitions for the two meta tables in it.
sqlite3 "$db" < db_update/metaschema.ddl

# Load the coontents of the two meta tables.
db_update/import_tables.py "$db" db_update/db_table.csv db_update/db_column.csv

# Create the rest of the tables (from the meta tables).
db_update/create_tables.py "$db"

# Load the fixed contents that's the same for all projects.
find db_update/fixed_data -name '*.csv' \
     -exec db_update/import_tables.py "$db" {} +

# Reload the backup data.
find "$dir/$db_backup_dir" -name '*.cols' \
     -exec db_update/load_table.py "$db" {} +

# Run table level python_update statements (if any).
db_update/do_updates.py "$db"
