#!/bin/bash

usage() {
    echo "usage: create_db directory" >&2
    exit 2
}

[ $# -eq 1 ] || usage

db_filename=python-avr.db
db_backup_dir=backups

set -e

dir="$1"
db="$dir/$db_filename"

# Save what's there first!
backup "$db"

# Nuke the database!
rm -f "$db"

# Create a new database with the definitions for the two meta tables in it.
sqlite3 "$db" < db_update/metaschema.ddl

# Load the contents of the two meta tables.
load_table.py -i "$db" db_update/db_table.csv db_update/db_column.csv

# Create the rest of the tables (from the meta tables).
create_tables.py "$db"

# Load the fixed contents that's the same for all projects.
find db_update/fixed_data -name '*.csv' -exec load_table.py -i "$db" {} +

# Reload the backup data.
find "$dir/$db_backup_dir" -name '*.csv' -exec load_table.py "$db" {} +

# Run table level python_update statements (if any).
do_updates.py "$db"
