#!/bin/bash

# make_machine_db machine.sql

usage() {
    echo make_machine_db machine.sql >&2
    exit 2
}

[ $# -eq 1 ] || usage

set -e

db_name=`basename "$1" .sql`.db

rm -f "$db_name"

echo Creating "$db_name"

for f in machine.ddl "$1" init.sql
do
    #echo reading "$f"
    sqlite3 -batch -init "$f" "$db_name" < /dev/null
done

